services:
  - type: web
    name: crop-recommendation-api
    env: python
    buildCommand: npm run build && pip install -r requirements.txt
    startCommand: gunicorn app:APP
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: MANDI_API_KEY
        sync: false
